---
title: "Analysis"
output: html_notebook
---

```{r}
library(RobustRankAggreg)
library(oligo)
library(ggplot2)
library(pheatmap)
library(affy)
library(affycoretools)
library(hgu133plus2.db)
library(limma)
library(dplyr)
library(clusterProfiler)
library(DOSE)
library(org.Hs.eg.db)
library(gProfileR)
```

```{r}
sdrf_location   <- file.path('data/', "GSE17351_RAW.txt")

SDRF            <- read.delim(sdrf_location)
rownames(SDRF)  <- SDRF$sample
SDRF            <- AnnotatedDataFrame(SDRF)

raw_data        <- oligo::read.celfiles(paste0("data/GSE17351_RAW/", 
                                        list.files("data/GSE17351_RAW/")),
                                        verbose = FALSE, phenoData = SDRF)

pData(raw_data)
```




```{r}
Biobase::exprs(raw_data)[1:5, 1:5]
```

```{r}
exp_raw <-Biobase::exprs(raw_data)
PCA_raw <- prcomp(t(exp_raw), scale. = FALSE)

percentVar  <- round(100*PCA_raw$sdev^2/sum(PCA_raw$sdev^2), 1)
sd_ratio    <- sqrt(percentVar[2] / percentVar[1])
dataGG      <- data.frame(PC1 = PCA_raw$x[,1], PC2 = PCA_raw$x[,2],
                          Group = pData(raw_data)$group)

ggplot(dataGG, aes(PC1, PC2)) +
  geom_point(aes(colour = Group)) +
  ggtitle("PCA plot of the log-transformed raw expression data") +
  xlab(paste0("PC1, VarExp: ", percentVar[1], "%")) +
  ylab(paste0("PC2, VarExp: ", percentVar[2], "%")) +
  theme(plot.title = element_text(hjust = 0.5))+
  coord_fixed(ratio = sd_ratio) +
  scale_color_manual(values = c("darkorange2", "dodgerblue4"))
```
```{r}
oligo::boxplot(raw_data, main = "Boxplot of log2-intensitites for the raw data")
```


```{r}
norm_data <- oligo::rma(raw_data)
norm_data <- annotateEset(norm_data, hgu133plus2.db)
fData(norm_data)
```

```{r}
oligo::boxplot(norm_data, main = "Boxplot of log2-intensitites for the raw data")
```

```{r}
row_medians_assayData <- Biobase::rowMedians(as.matrix(Biobase::exprs(norm_data)))
RLE_data              <- sweep(Biobase::exprs(norm_data), 1, row_medians_assayData)
RLE_data              <- as.data.frame(RLE_data)
RLE_data_gathered     <- tidyr::gather(RLE_data, patient_array, log2_expression_deviation)
ggplot2::ggplot(RLE_data_gathered, aes(patient_array, log2_expression_deviation)) +
  geom_boxplot(outlier.shape = NA) + ylim(c(-1, 1)) + 
  theme(axis.text.x = element_text(colour = "aquamarine4", angle = 60, 
                                   size = 6.5, hjust = 1 , face = "bold"))
```

```{r}
exp_norm <- Biobase::exprs(norm_data)
PCA_norm <- prcomp(t(exp_norm), scale. = FALSE)

percentVar  <- round(100*PCA_norm$sdev^2/sum(PCA_norm$sdev^2), 1)
sd_ratio    <- sqrt(percentVar[2] / percentVar[1])
dataGG      <- data.frame(PC1 = PCA_norm$x[,1], PC2 = PCA_norm$x[,2],
                          Group = pData(raw_data)$group)

ggplot(dataGG, aes(PC1, PC2)) +
  geom_point(aes(colour = Group)) +
  ggtitle("PCA plot of the calibrated data") +
  xlab(paste0("PC1, VarExp: ", percentVar[1], "%")) +
  ylab(paste0("PC2, VarExp: ", percentVar[2], "%")) +
  theme(plot.title = element_text(hjust = 0.5))+
  coord_fixed(ratio = sd_ratio) +
  scale_color_manual(values = c("darkorange2", "dodgerblue4"))
```

```{r}
annotation_for_heatmap <- data.frame(Group = pData(norm_data)$group)
row.names(annotation_for_heatmap) <- row.names(pData(norm_data))

dists <- as.matrix(dist(t(Biobase::exprs(norm_data)), method = "manhattan"))
rownames(dists) <- row.names(pData(norm_data))
hmcol <- rev(colorRampPalette(RColorBrewer::brewer.pal(9, "YlOrRd"))(255))
colnames(dists) <- NULL
diag(dists) <- NA
ann_colors <- list(Group = c(Normal = "green", ESCC = "red"))

pheatmap(dists, col = (hmcol),
         annotation_row = annotation_for_heatmap,
         annotation_colors = ann_colors,
         legend = TRUE,
         treeheight_row = 0,
         legend_breaks = c(min(dists, na.rm = TRUE),
                           max(dists, na.rm = TRUE)),
         legend_labels = (c("small distance", "large distance")),
         main = "Clustering heatmap for the calibrated samples")
```

```{r}
design                <- model.matrix(~ 0 + factor(rep(1:2, 5)))
colnames(design)      <- c("Normal", "ESCC")
contrast.matrix       <- makeContrasts(Normal-ESCC, levels = design)
fit                   <- lmFit(exprs(norm_data), design)

plotSA(fit, main = 'Standard deviation versus average log expression')
fit               <- contrasts.fit(fit, contrast.matrix)
#fit_adc               <- eBayes(fit_adc, trend = TRUE, robust = TRUE)
fit               <- eBayes(fit)
```
```{r}
results <- decideTests(fit)
results
summary(results)
```

## Porównanie Kontrola~Margines
```{r}
results <- topTable(fit, coef = "Normal - ESCC", adjust = "BH", number = Inf)
plotMD(fit, coef = "Normal - ESCC", status = results, cex = 0.2)
```

```{r}
results %>% filter(abs(logFC)>2, adj.P.Val < 0.05)
```
```{r}
filtered_results <- results %>% filter(abs(logFC)>2, adj.P.Val < 0.05)
```

```{r}
rownames(filtered_results)
```

```{r}

```


```{r}
scc_ego <- enrichGO(na.omit(fData(norm_data)[rownames(filtered_results), 'ENTREZID']), 
                    'org.Hs.eg.db', ont = "BP", pvalueCutoff = 0.05, pAdjustMethod = "none")
head(scc_ego@result, 10)
dotplot(scc_ego)
```

```{r}
descc <- top_scc_ext[!is.na(top_scc_ext$LOCUSLINK_ID), ]$logFC
names(descc) <- top_scc_ext[!is.na(top_scc_ext$LOCUSLINK_ID), ]$LOCUSLINK_ID
edoscc <- enrichDGN(names(descc),  pvalueCutoff = 0.05)
head(edoscc)
barplot(edoscc, showCategory=20, title = 'Enrichment score')
```

```{r}
```


```{r}
```


```{r}
```


```{r}
gse <- gseGO(geneList=order(as.numeric(na.omit(fData(norm_data)[rownames(filtered_results), 'ENTREZID']))), 
             ont ="ALL", 
             keyType = "ENTREZID", 
             nPerm = 10000, 
             minGSSize = 3, 
             maxGSSize = 800, 
             pvalueCutoff = 0.05, 
             verbose = TRUE, 
             OrgDb = org.Hs.eg.db, 
             pAdjustMethod = "none")
```
```{r}
dotplot(gse, showCategory=10, split=".sign")
```



```{r}
data(gcSample)
xx <- compareCluster(na.omit(fData(norm_data)[rownames(filtered_results), 'ENTREZID']), 
                     fun="enrichKEGG", organism="hsa", pvalueCutoff=0.05)

plot(xx, type="dot", caption="KEGG Enrichment Comparison")
```

```{r}
glist <- list(sample(letters, 4), sample(letters, 10), sample(letters, 12))
aggregateRanks(glist = glist, N = length(letters))
```


```{r}
```


```{r}
```


```{r}
```




















